# Generated by Django 5.0.2 on 2025-01-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
